"""add created_at to refresh tokens

Revision ID: 6c7b0e89b9f6
Revises: b5b8e30386f4
Create Date: 2026-06-29 15:03:41.644133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7b0e89b9f6'
down_revision: Union[str, Sequence[str], None] = 'b5b8e30386f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'created_at')
    # ### end Alembic commands ###
