"""normalize exercise metadata

Revision ID: a201e0b828f4
Revises: cd6cc75e4d4f
Create Date: 2026-06-30 14:16:45.502982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a201e0b828f4'
down_revision: Union[str, Sequence[str], None] = 'cd6cc75e4d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_difficulties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movement_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('exercises', sa.Column('difficulty_id', sa.UUID(), nullable=False))
    op.add_column('exercises', sa.Column('movement_pattern_id', sa.UUID(), nullable=False))
    op.create_foreign_key("fk_exercises_difficulty","exercises","exercise_difficulties", ["difficulty_id"],["id"],)
    op.create_foreign_key("fk_exercises_movement_pattern","exercises","movement_patterns",["movement_pattern_id"],["id"],)
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'movement_pattern')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('movement_pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint("fk_exercises_movement_pattern","exercises",type_="foreignkey",)
    op.drop_constraint("fk_exercises_difficulty","exercises",type_="foreignkey",)
    op.drop_column('exercises', 'movement_pattern_id')
    op.drop_column('exercises', 'difficulty_id')
    op.drop_table('movement_patterns')
    op.drop_table('exercise_difficulties')
    # ### end Alembic commands ###
